site_name: AdPlatform

nav:
#  - Home: 'index.md'
  - Publisher:
    - 'publisher/publisher.md'
    - Dashboard: 'publisher/dashboard.md'
    - Endpoint: 'publisher/end_points.md'
    - Apps/Domain: 'publisher/apps_domain.md'
    - Rules: 'publisher/rules.md'
    - Reports:
        - Monetization: 'publisher/reports/monetization.md'
        - Failed Bid: 'publisher/reports/failed_bids.md'
        - Invalid Bid: 'publisher/reports/invalid_bids.md'
    - Billing: 'publisher/billing.md'
    - ADS.TXT: 'publisher/adstxt.md'
    - Profile Settings: 'publisher/profile_settings.md'


  - Advertiser:
    - 'advertise.md'
    - Dashboard: 'advertisers/dashboard.md'
    - Endpoint: 'advertisers/end_points.md'
    - Apps/Domain: 'advertisers/apps_domain.md'
    - CID/CRID:
        - Campaigns: 'advertisers/crid/campaigns.md'
        - Creatives: 'advertisers/crid/creatives.md'
        - Targeting: 'advertisers/crid/targeting.md'
    - Rules: 'advertisers/rules.md'
    - Reports:
        - Monetization: 'advertisers/reports/monetization.md'
        - Failed Bid: 'advertisers/reports/failed_bids.md'
        - Invalid Bid: 'advertisers/reports/invalid_bids.md'
    - Billing: 'advertisers/billing.md'
    - ADS.TXT: 'advertisers/adstxt.md'
    - Profile Settings: 'advertisers/profile_settings.md'

  - Admin Panel:
    - 'admin/admin.md'
    - Dashboard: 'admin/dashboard.md'
    - Reports:
        - Direct Campaigns: 'admin/reports/direct_campaigns.md'
        - End-points: 'admin/reports/end_points.md'
        - Invalid Transcation: 'admin/reports/invalid_transaction.md'
        - Failed Request: 'admin/reports/failed_request.md'
    - Accounts:
      - Pub Account: 'admin/accounts/publishers_account.md'
      - Adv Account: 'admin/accounts/advertisers_account.md'
    - Profile:
        - Pub Account: 'admin/profile/publishers_profile.md'
        - Adv Account: 'admin/profile/advertisers_profile.md'
    - End-Points:
        - Pub EP: 'admin/endpoints/pub_ep.md'
        - Adv EP: 'admin/endpoints/adv_ep.md'
    - EP MAP: 'admin/endpoint_mapping.md'
    - Apps/Domains:
        - Pub Apps/Sites: 'admin/appsdomain/pub-appssite.md'
        - Adv Apps/Sites: 'admin/appsdomain/adv-appssite.md'
    - CID/CRID:
        - Campaigns: 'admin/crid/campaigns.md'
        - Creatives: 'admin/crid/creatives.md'
        - Targeting: 'admin/crid/targeting.md'
    - Billing:
        - Pub Billing: 'admin/billing/pub-billing.md'
        - Adv Billing: 'admin/billing/adv-billing.md'

theme:
#  logo: assets/logo.svg
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  font:
    text: Roboto 300


markdown_extensions:
    - toc:
        permalink: true
    - tables
    - attr_list
    - pymdownx.emoji
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

plugins:
  - search
  - section-index
  - mermaid2
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 90%
      height: auto
      zoomable: true
      draggable: true

extra_css:
  - custom.css