site_name: AdPlatform

nav:
#  - Home: index.md
  - Publisher:
    - publisher/publisher.md
    - Endpoint: 'publisher/end_points.md'
    - Dashboard: 'publisher/dashboard.md'
    - Apps/Domain: 'publisher/apps_domain.md'
    - Rules: 'publisher/rules.md'
    - Reports:
        - Monetization: 'publisher/reports/monetization.md'
        - Failed Bid: 'publisher/reports/failed_bids.md'
        - Invalid Bid: 'publisher/reports/invalid_bids.md'
    - Billing: 'publisher/billing.md'
    - ADS.TXT: 'publisher/adstxt.md'
    - Profile Settings: 'publisher/profile_settings.md'


  - Advertiser: advertise.md

  - Admin Panel: admin_panel.md

theme:
#  logo: assets/logo.svg
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  font:
    text: Roboto 300


markdown_extensions:
    - toc:
        permalink: true
    - tables
    - attr_list
    - pymdownx.emoji
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

plugins:
  - search
  - section-index
  - mermaid2
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 90%
      height: auto
      zoomable: true
      draggable: true

extra_css:
  - custom.css